# Default values for egress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: livekit/egress
  pullPolicy: IfNotPresent

egress:
  logLevel: info
  healthPort: 8080
  prometheusPort: 9090

terminationGracePeriodSeconds: 3600

nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: false

nodeSelector: {}

resources: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"
  linkerd.io/inject: disabled

podSecurityContext: {}

securityContext: {}

tolerations: []

affinity: {}
