# Default values for ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: livekit/ingress
  pullPolicy: IfNotPresent

ingress:
  logging:
    level: info
  healthPort: 7888
  prometheusPort: 7889
  httpRelayPort: 9090
  rtmpPort: 1935
  whipPort: 8080
  rtcConfig:
    useExternalIp: true
    udpPort: 7885
  redis: {}

  cpuCost:
    rtmpCpuCost: 2
    whipCpuCost: 2
    whipBypassTranscodingCpuCost: 0.1

loadBalancer:
  servicePort: 7888
  annotations: {}

terminationGracePeriodSeconds: 3600

nameOverride: ""
fullnameOverride: ""

autoscaling:
  enabled: false

nodeSelector: {}

resources: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

podHostNetwork: true

podAnnotations:
  sidecar.istio.io/inject: "false"
  linkerd.io/inject: disabled

podSecurityContext: {}

securityContext: {}

tolerations: []

affinity: {}
